name: flutter_ffi_uvc
description: UVC camera plugin based on libuvc, with live preview, frame access, and device controls.
version: 0.7.0
repository: https://github.com/cornpip/flutter_ffi_uvc

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

topics:
  - camera
  - usb
  - uvc
  - ffi
  - libuvc

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.3

dev_dependencies:
  ffigen: ^20.1.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.cornpip.flutter_ffi_uvc
        pluginClass: FlutterFfiUvcPlugin
        ffiPlugin: true
