// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Bindings for `src/flutter_ffi_uvc.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class FlutterFfiUvcBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  FlutterFfiUvcBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  FlutterFfiUvcBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// A very short-lived native function.
  ///
  /// For very short-lived functions, it is fine to call them on the main isolate.
  /// They will block the Dart execution while running the native function, so
  /// only do this for native functions which are guaranteed to be short-lived.
  int sum(int a, int b) {
    return _sum(a, b);
  }

  late final _sumPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>('sum');
  late final _sum = _sumPtr.asFunction<int Function(int, int)>();

  /// A longer lived native function, which occupies the thread calling it.
  ///
  /// Do not call these kind of native functions in the main isolate. They will
  /// block Dart execution. This will cause dropped frames in Flutter applications.
  /// Instead, call these native functions on a separate isolate.
  int sum_long_running(int a, int b) {
    return _sum_long_running(a, b);
  }

  late final _sum_long_runningPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>(
        'sum_long_running',
      );
  late final _sum_long_running = _sum_long_runningPtr
      .asFunction<int Function(int, int)>();

  int uvc_open_fd(int fd) {
    return _uvc_open_fd(fd);
  }

  late final _uvc_open_fdPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>('uvc_open_fd');
  late final _uvc_open_fd = _uvc_open_fdPtr.asFunction<int Function(int)>();

  int uvc_start_preview(int frame_format, int width, int height, int fps) {
    return _uvc_start_preview(frame_format, width, height, fps);
  }

  late final _uvc_start_previewPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int, ffi.Int, ffi.Int)>
      >('uvc_start_preview');
  late final _uvc_start_preview = _uvc_start_previewPtr
      .asFunction<int Function(int, int, int, int)>();

  void uvc_stop_preview() {
    return _uvc_stop_preview();
  }

  late final _uvc_stop_previewPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('uvc_stop_preview');
  late final _uvc_stop_preview = _uvc_stop_previewPtr
      .asFunction<void Function()>();

  void uvc_close_device() {
    return _uvc_close_device();
  }

  late final _uvc_close_devicePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('uvc_close_device');
  late final _uvc_close_device = _uvc_close_devicePtr
      .asFunction<void Function()>();

  int uvc_is_previewing() {
    return _uvc_is_previewing();
  }

  late final _uvc_is_previewingPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('uvc_is_previewing');
  late final _uvc_is_previewing = _uvc_is_previewingPtr
      .asFunction<int Function()>();

  int uvc_frame_width() {
    return _uvc_frame_width();
  }

  late final _uvc_frame_widthPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('uvc_frame_width');
  late final _uvc_frame_width = _uvc_frame_widthPtr
      .asFunction<int Function()>();

  int uvc_frame_height() {
    return _uvc_frame_height();
  }

  late final _uvc_frame_heightPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('uvc_frame_height');
  late final _uvc_frame_height = _uvc_frame_heightPtr
      .asFunction<int Function()>();

  int uvc_copy_latest_frame_rgba(
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
  ) {
    return _uvc_copy_latest_frame_rgba(buffer, buffer_length);
  }

  late final _uvc_copy_latest_frame_rgbaPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Uint8>, ffi.Int)>
      >('uvc_copy_latest_frame_rgba');
  late final _uvc_copy_latest_frame_rgba = _uvc_copy_latest_frame_rgbaPtr
      .asFunction<int Function(ffi.Pointer<ffi.Uint8>, int)>();

  int uvc_copy_latest_frame_rgba_with_metadata(
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
    ffi.Pointer<ffi.Int> out_width,
    ffi.Pointer<ffi.Int> out_height,
    ffi.Pointer<ffi.Int64> out_sequence,
  ) {
    return _uvc_copy_latest_frame_rgba_with_metadata(
      buffer,
      buffer_length,
      out_width,
      out_height,
      out_sequence,
    );
  }

  late final _uvc_copy_latest_frame_rgba_with_metadataPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int64>,
          )
        >
      >('uvc_copy_latest_frame_rgba_with_metadata');
  late final _uvc_copy_latest_frame_rgba_with_metadata =
      _uvc_copy_latest_frame_rgba_with_metadataPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Uint8>,
              int,
              ffi.Pointer<ffi.Int>,
              ffi.Pointer<ffi.Int>,
              ffi.Pointer<ffi.Int64>,
            )
          >();

  int uvc_copy_latest_frame_rgba_transformed(
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
    int rotation,
    int flip_h,
    int flip_v,
    ffi.Pointer<ffi.Int> out_width,
    ffi.Pointer<ffi.Int> out_height,
    ffi.Pointer<ffi.Int64> out_sequence,
  ) {
    return _uvc_copy_latest_frame_rgba_transformed(
      buffer,
      buffer_length,
      rotation,
      flip_h,
      flip_v,
      out_width,
      out_height,
      out_sequence,
    );
  }

  late final _uvc_copy_latest_frame_rgba_transformedPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int64>,
          )
        >
      >('uvc_copy_latest_frame_rgba_transformed');
  late final _uvc_copy_latest_frame_rgba_transformed =
      _uvc_copy_latest_frame_rgba_transformedPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Uint8>,
              int,
              int,
              int,
              int,
              ffi.Pointer<ffi.Int>,
              ffi.Pointer<ffi.Int>,
              ffi.Pointer<ffi.Int64>,
            )
          >();

  /// Captures the latest decodable frame as JPEG bytes.
  ///
  /// For MJPEG streams the raw camera frame is returned unmodified (lossless,
  /// no re-encode) and [quality] is ignored. For other formats the latest
  /// decoded frame is encoded with libjpeg at [quality] (1-100; out-of-range
  /// values are clamped, <=0 uses 90).
  ///
  /// A buffer of uvc_frame_width()*uvc_frame_height()*4 bytes is always large
  /// enough. Returns the number of JPEG bytes written to [buffer], or 0 on
  /// failure (see uvc_last_error).
  int uvc_capture_jpeg(
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
    int quality,
    ffi.Pointer<ffi.Int> out_width,
    ffi.Pointer<ffi.Int> out_height,
    ffi.Pointer<ffi.Int64> out_sequence,
  ) {
    return _uvc_capture_jpeg(
      buffer,
      buffer_length,
      quality,
      out_width,
      out_height,
      out_sequence,
    );
  }

  late final _uvc_capture_jpegPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
            ffi.Int,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int64>,
          )
        >
      >('uvc_capture_jpeg');
  late final _uvc_capture_jpeg = _uvc_capture_jpegPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Uint8>,
          int,
          int,
          ffi.Pointer<ffi.Int>,
          ffi.Pointer<ffi.Int>,
          ffi.Pointer<ffi.Int64>,
        )
      >();

  int uvc_latest_frame_sequence() {
    return _uvc_latest_frame_sequence();
  }

  late final _uvc_latest_frame_sequencePtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
        'uvc_latest_frame_sequence',
      );
  late final _uvc_latest_frame_sequence = _uvc_latest_frame_sequencePtr
      .asFunction<int Function()>();

  void uvc_set_frame_listener(uvc_frame_listener_t listener) {
    return _uvc_set_frame_listener(listener);
  }

  late final _uvc_set_frame_listenerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(uvc_frame_listener_t)>>(
        'uvc_set_frame_listener',
      );
  late final _uvc_set_frame_listener = _uvc_set_frame_listenerPtr
      .asFunction<void Function(uvc_frame_listener_t)>();

  void uvc_set_error_listener(uvc_error_listener_t listener) {
    return _uvc_set_error_listener(listener);
  }

  late final _uvc_set_error_listenerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(uvc_error_listener_t)>>(
        'uvc_set_error_listener',
      );
  late final _uvc_set_error_listener = _uvc_set_error_listenerPtr
      .asFunction<void Function(uvc_error_listener_t)>();

  int uvc_get_stream_stats_json(
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
  ) {
    return _uvc_get_stream_stats_json(buffer, buffer_length);
  }

  late final _uvc_get_stream_stats_jsonPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Uint8>, ffi.Int)>
      >('uvc_get_stream_stats_json');
  late final _uvc_get_stream_stats_json = _uvc_get_stream_stats_jsonPtr
      .asFunction<int Function(ffi.Pointer<ffi.Uint8>, int)>();

  int uvc_get_supported_modes_json(
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
  ) {
    return _uvc_get_supported_modes_json(buffer, buffer_length);
  }

  late final _uvc_get_supported_modes_jsonPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Uint8>, ffi.Int)>
      >('uvc_get_supported_modes_json');
  late final _uvc_get_supported_modes_json = _uvc_get_supported_modes_jsonPtr
      .asFunction<int Function(ffi.Pointer<ffi.Uint8>, int)>();

  ffi.Pointer<ffi.Char> uvc_last_error() {
    return _uvc_last_error();
  }

  late final _uvc_last_errorPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'uvc_last_error',
      );
  late final _uvc_last_error = _uvc_last_errorPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  void uvc_set_log_level(int level) {
    return _uvc_set_log_level(level);
  }

  late final _uvc_set_log_levelPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>(
        'uvc_set_log_level',
      );
  late final _uvc_set_log_level = _uvc_set_log_levelPtr
      .asFunction<void Function(int)>();

  /// Preview transform: rotation is 0, 90, 180, or 270 (clockwise degrees).
  /// flip_h mirrors the output left-right; flip_v mirrors it top-bottom.
  /// Transforms are applied during preview blit to the attached Flutter Texture
  /// and do not affect the shared RGBA buffer returned by copyLatestFrame.
  void uvc_set_preview_transform(int rotation, int flip_h, int flip_v) {
    return _uvc_set_preview_transform(rotation, flip_h, flip_v);
  }

  late final _uvc_set_preview_transformPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int, ffi.Int, ffi.Int)>>(
        'uvc_set_preview_transform',
      );
  late final _uvc_set_preview_transform = _uvc_set_preview_transformPtr
      .asFunction<void Function(int, int, int)>();

  /// Returns JSON array of all controls the device supports, with min/max/def/cur/res fields.
  /// Returns number of bytes written, or 0 on failure.
  int uvc_ctrl_get_all_json(ffi.Pointer<ffi.Uint8> buffer, int buffer_length) {
    return _uvc_ctrl_get_all_json(buffer, buffer_length);
  }

  late final _uvc_ctrl_get_all_jsonPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Uint8>, ffi.Int)>
      >('uvc_ctrl_get_all_json');
  late final _uvc_ctrl_get_all_json = _uvc_ctrl_get_all_jsonPtr
      .asFunction<int Function(ffi.Pointer<ffi.Uint8>, int)>();

  /// Returns JSON array of controls present in descriptor bmControls only.
  /// Debug helper: does not probe GET_CUR/GET_MIN/GET_MAX.
  int uvc_ctrl_get_bm_controls_json(
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
  ) {
    return _uvc_ctrl_get_bm_controls_json(buffer, buffer_length);
  }

  late final _uvc_ctrl_get_bm_controls_jsonPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Uint8>, ffi.Int)>
      >('uvc_ctrl_get_bm_controls_json');
  late final _uvc_ctrl_get_bm_controls_json = _uvc_ctrl_get_bm_controls_jsonPtr
      .asFunction<int Function(ffi.Pointer<ffi.Uint8>, int)>();

  /// Returns the current value of a control. Returns INT32_MIN on error.
  int uvc_ctrl_get(int ctrl_id) {
    return _uvc_ctrl_get(ctrl_id);
  }

  late final _uvc_ctrl_getPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Int)>>('uvc_ctrl_get');
  late final _uvc_ctrl_get = _uvc_ctrl_getPtr.asFunction<int Function(int)>();

  /// Sets a control value. Returns 0 (UVC_SUCCESS) on success, negative on error.
  int uvc_ctrl_set(int ctrl_id, int value) {
    return _uvc_ctrl_set(ctrl_id, value);
  }

  late final _uvc_ctrl_setPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int32)>>(
        'uvc_ctrl_set',
      );
  late final _uvc_ctrl_set = _uvc_ctrl_setPtr
      .asFunction<int Function(int, int)>();

  /// Compound controls that cannot be represented as a single integer value.
  int uvc_get_white_balance_component_json(
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
  ) {
    return _uvc_get_white_balance_component_json(buffer, buffer_length);
  }

  late final _uvc_get_white_balance_component_jsonPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Uint8>, ffi.Int)>
      >('uvc_get_white_balance_component_json');
  late final _uvc_get_white_balance_component_json =
      _uvc_get_white_balance_component_jsonPtr
          .asFunction<int Function(ffi.Pointer<ffi.Uint8>, int)>();

  int uvc_set_white_balance_component_values(int blue, int red) {
    return _uvc_set_white_balance_component_values(blue, red);
  }

  late final _uvc_set_white_balance_component_valuesPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Uint16, ffi.Uint16)>>(
        'uvc_set_white_balance_component_values',
      );
  late final _uvc_set_white_balance_component_values =
      _uvc_set_white_balance_component_valuesPtr
          .asFunction<int Function(int, int)>();

  int uvc_get_focus_rel_json(ffi.Pointer<ffi.Uint8> buffer, int buffer_length) {
    return _uvc_get_focus_rel_json(buffer, buffer_length);
  }

  late final _uvc_get_focus_rel_jsonPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Uint8>, ffi.Int)>
      >('uvc_get_focus_rel_json');
  late final _uvc_get_focus_rel_json = _uvc_get_focus_rel_jsonPtr
      .asFunction<int Function(ffi.Pointer<ffi.Uint8>, int)>();

  int uvc_set_focus_rel_values(int focus_rel, int speed) {
    return _uvc_set_focus_rel_values(focus_rel, speed);
  }

  late final _uvc_set_focus_rel_valuesPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int8, ffi.Uint8)>>(
        'uvc_set_focus_rel_values',
      );
  late final _uvc_set_focus_rel_values = _uvc_set_focus_rel_valuesPtr
      .asFunction<int Function(int, int)>();

  int uvc_get_zoom_rel_json(ffi.Pointer<ffi.Uint8> buffer, int buffer_length) {
    return _uvc_get_zoom_rel_json(buffer, buffer_length);
  }

  late final _uvc_get_zoom_rel_jsonPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Uint8>, ffi.Int)>
      >('uvc_get_zoom_rel_json');
  late final _uvc_get_zoom_rel_json = _uvc_get_zoom_rel_jsonPtr
      .asFunction<int Function(ffi.Pointer<ffi.Uint8>, int)>();

  int uvc_set_zoom_rel_values(int zoom_rel, int digital_zoom, int speed) {
    return _uvc_set_zoom_rel_values(zoom_rel, digital_zoom, speed);
  }

  late final _uvc_set_zoom_rel_valuesPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Int8, ffi.Uint8, ffi.Uint8)>
      >('uvc_set_zoom_rel_values');
  late final _uvc_set_zoom_rel_values = _uvc_set_zoom_rel_valuesPtr
      .asFunction<int Function(int, int, int)>();

  int uvc_get_pantilt_abs_json(
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
  ) {
    return _uvc_get_pantilt_abs_json(buffer, buffer_length);
  }

  late final _uvc_get_pantilt_abs_jsonPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Uint8>, ffi.Int)>
      >('uvc_get_pantilt_abs_json');
  late final _uvc_get_pantilt_abs_json = _uvc_get_pantilt_abs_jsonPtr
      .asFunction<int Function(ffi.Pointer<ffi.Uint8>, int)>();

  int uvc_set_pantilt_abs_values(int pan, int tilt) {
    return _uvc_set_pantilt_abs_values(pan, tilt);
  }

  late final _uvc_set_pantilt_abs_valuesPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int32, ffi.Int32)>>(
        'uvc_set_pantilt_abs_values',
      );
  late final _uvc_set_pantilt_abs_values = _uvc_set_pantilt_abs_valuesPtr
      .asFunction<int Function(int, int)>();

  int uvc_get_pantilt_rel_json(
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
  ) {
    return _uvc_get_pantilt_rel_json(buffer, buffer_length);
  }

  late final _uvc_get_pantilt_rel_jsonPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Uint8>, ffi.Int)>
      >('uvc_get_pantilt_rel_json');
  late final _uvc_get_pantilt_rel_json = _uvc_get_pantilt_rel_jsonPtr
      .asFunction<int Function(ffi.Pointer<ffi.Uint8>, int)>();

  int uvc_set_pantilt_rel_values(
    int pan_rel,
    int pan_speed,
    int tilt_rel,
    int tilt_speed,
  ) {
    return _uvc_set_pantilt_rel_values(
      pan_rel,
      pan_speed,
      tilt_rel,
      tilt_speed,
    );
  }

  late final _uvc_set_pantilt_rel_valuesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Int8, ffi.Uint8, ffi.Int8, ffi.Uint8)
        >
      >('uvc_set_pantilt_rel_values');
  late final _uvc_set_pantilt_rel_values = _uvc_set_pantilt_rel_valuesPtr
      .asFunction<int Function(int, int, int, int)>();

  int uvc_get_roll_rel_json(ffi.Pointer<ffi.Uint8> buffer, int buffer_length) {
    return _uvc_get_roll_rel_json(buffer, buffer_length);
  }

  late final _uvc_get_roll_rel_jsonPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Uint8>, ffi.Int)>
      >('uvc_get_roll_rel_json');
  late final _uvc_get_roll_rel_json = _uvc_get_roll_rel_jsonPtr
      .asFunction<int Function(ffi.Pointer<ffi.Uint8>, int)>();

  int uvc_set_roll_rel_values(int roll_rel, int speed) {
    return _uvc_set_roll_rel_values(roll_rel, speed);
  }

  late final _uvc_set_roll_rel_valuesPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int8, ffi.Uint8)>>(
        'uvc_set_roll_rel_values',
      );
  late final _uvc_set_roll_rel_values = _uvc_set_roll_rel_valuesPtr
      .asFunction<int Function(int, int)>();

  int uvc_get_digital_window_json(
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
  ) {
    return _uvc_get_digital_window_json(buffer, buffer_length);
  }

  late final _uvc_get_digital_window_jsonPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Uint8>, ffi.Int)>
      >('uvc_get_digital_window_json');
  late final _uvc_get_digital_window_json = _uvc_get_digital_window_jsonPtr
      .asFunction<int Function(ffi.Pointer<ffi.Uint8>, int)>();

  int uvc_set_digital_window_values(
    int window_top,
    int window_left,
    int window_bottom,
    int window_right,
    int num_steps,
    int num_steps_units,
  ) {
    return _uvc_set_digital_window_values(
      window_top,
      window_left,
      window_bottom,
      window_right,
      num_steps,
      num_steps_units,
    );
  }

  late final _uvc_set_digital_window_valuesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Uint16,
            ffi.Uint16,
            ffi.Uint16,
            ffi.Uint16,
            ffi.Uint16,
            ffi.Uint16,
          )
        >
      >('uvc_set_digital_window_values');
  late final _uvc_set_digital_window_values = _uvc_set_digital_window_valuesPtr
      .asFunction<int Function(int, int, int, int, int, int)>();

  int uvc_get_region_of_interest_json(
    ffi.Pointer<ffi.Uint8> buffer,
    int buffer_length,
  ) {
    return _uvc_get_region_of_interest_json(buffer, buffer_length);
  }

  late final _uvc_get_region_of_interest_jsonPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Uint8>, ffi.Int)>
      >('uvc_get_region_of_interest_json');
  late final _uvc_get_region_of_interest_json =
      _uvc_get_region_of_interest_jsonPtr
          .asFunction<int Function(ffi.Pointer<ffi.Uint8>, int)>();

  int uvc_set_region_of_interest_values(
    int roi_top,
    int roi_left,
    int roi_bottom,
    int roi_right,
    int auto_controls,
  ) {
    return _uvc_set_region_of_interest_values(
      roi_top,
      roi_left,
      roi_bottom,
      roi_right,
      auto_controls,
    );
  }

  late final _uvc_set_region_of_interest_valuesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Uint16,
            ffi.Uint16,
            ffi.Uint16,
            ffi.Uint16,
            ffi.Uint16,
          )
        >
      >('uvc_set_region_of_interest_values');
  late final _uvc_set_region_of_interest_values =
      _uvc_set_region_of_interest_valuesPtr
          .asFunction<int Function(int, int, int, int, int)>();
}

typedef uvc_frame_listener_tFunction = ffi.Void Function(ffi.Int64 sequence);
typedef Dartuvc_frame_listener_tFunction = void Function(int sequence);
typedef uvc_frame_listener_t =
    ffi.Pointer<ffi.NativeFunction<uvc_frame_listener_tFunction>>;
typedef uvc_error_listener_tFunction =
    ffi.Void Function(ffi.Pointer<ffi.Char> message);
typedef Dartuvc_error_listener_tFunction =
    void Function(ffi.Pointer<ffi.Char> message);
typedef uvc_error_listener_t =
    ffi.Pointer<ffi.NativeFunction<uvc_error_listener_tFunction>>;

const int UVC_CTRL_ID_BRIGHTNESS = 1;

const int UVC_CTRL_ID_CONTRAST = 2;

const int UVC_CTRL_ID_HUE = 3;

const int UVC_CTRL_ID_SATURATION = 4;

const int UVC_CTRL_ID_SHARPNESS = 5;

const int UVC_CTRL_ID_GAMMA = 6;

const int UVC_CTRL_ID_GAIN = 7;

const int UVC_CTRL_ID_BACKLIGHT_COMPENSATION = 8;

const int UVC_CTRL_ID_WHITE_BALANCE_TEMPERATURE = 9;

const int UVC_CTRL_ID_WHITE_BALANCE_TEMP_AUTO = 10;

const int UVC_CTRL_ID_POWER_LINE_FREQUENCY = 11;

const int UVC_CTRL_ID_CONTRAST_AUTO = 12;

const int UVC_CTRL_ID_HUE_AUTO = 13;

const int UVC_CTRL_ID_WHITE_BALANCE_COMPONENT_AUTO = 14;

const int UVC_CTRL_ID_DIGITAL_MULTIPLIER = 15;

const int UVC_CTRL_ID_DIGITAL_MULTIPLIER_LIMIT = 16;

const int UVC_CTRL_ID_ANALOG_VIDEO_STANDARD = 17;

const int UVC_CTRL_ID_ANALOG_LOCK_STATUS = 18;

const int UVC_CTRL_ID_EXPOSURE_ABS = 20;

const int UVC_CTRL_ID_AE_MODE = 21;

const int UVC_CTRL_ID_AE_PRIORITY = 22;

const int UVC_CTRL_ID_FOCUS_ABS = 23;

const int UVC_CTRL_ID_FOCUS_AUTO = 24;

const int UVC_CTRL_ID_ZOOM_ABS = 25;

const int UVC_CTRL_ID_SCANNING_MODE = 26;

const int UVC_CTRL_ID_EXPOSURE_REL = 27;

const int UVC_CTRL_ID_IRIS_ABS = 28;

const int UVC_CTRL_ID_IRIS_REL = 29;

const int UVC_CTRL_ID_ROLL_ABS = 30;

const int UVC_CTRL_ID_PRIVACY = 31;

const int UVC_CTRL_ID_FOCUS_SIMPLE = 32;
